import React from 'react'
import AllDiseaseVsNoDisease from '../Graphs/ModelGenerated/AllDiseaseVsNoDisease.png'
import EachFeatureEffect from '../Graphs/ModelGenerated/EachFeatureEffect.png'

export default function Graphs(props) {
    return (

        <>
            {props.graphsState === true ?

                (<div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img src={EachFeatureEffect} alt="Lights" style={{ width: "100%" }} />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img src={AllDiseaseVsNoDisease} alt="Nature" style={{ width: "100%" }} />
                            </div>
                        </div>
                    </div>

                    <div>
                        <p><strong>The graphs are based on data generated by model</strong></p>
                    </div>
                </div>)

                : ""}
        </>

    )
}
